name: Deploy React Sandbox App
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cygnetops/react-test npm test -- --coverage

      - run: docker build -t olegsudakov/multi-client ./client
      - run: docker build -t olegsudakov/multi-nginx ./nginx
      - run: docker build -t olegsudakov/multi-server ./server
      - run: docker build -t olegsudakov/multi-worker ./worker

      - run: docker push olegsudakov/multi-client
      - run: docker push olegsudakov/multi-nginx
      - run: docker push olegsudakov/multi-server
      - run: docker push olegsudakov/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react-sandbox
      #     environment_name: Dockerreactsandbox-env
      #     existing_bucket_name: elasticbeanstalk-eu-west-3-498112017332
      #     region: eu-west-3
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
      #     use_existing_version_if_available: true